# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcribe.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transcribe.proto\x12\ntranscribe\";\n\x11TranscribeRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\"\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2`\n\x11TranscribeService\x12K\n\nTranscribe\x12\x1d.transcribe.TranscribeRequest\x1a\x1e.transcribe.TranscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=32
  _globals['_TRANSCRIBEREQUEST']._serialized_end=91
  _globals['_TRANSCRIBERESPONSE']._serialized_start=93
  _globals['_TRANSCRIBERESPONSE']._serialized_end=127
  _globals['_TRANSCRIBESERVICE']._serialized_start=129
  _globals['_TRANSCRIBESERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
