"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TranscribeRequest(google.protobuf.message.Message):
    """TranscribeRequest is the request message for transcribing an audio file."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_CONTENT_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    file_content: builtins.bytes
    """The audio file content."""
    filename: builtins.str
    """The filename of the audio file."""
    def __init__(
        self,
        *,
        file_content: builtins.bytes = ...,
        filename: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file_content", b"file_content", "filename", b"filename"]) -> None: ...

global___TranscribeRequest = TranscribeRequest

@typing.final
class TranscribeResponse(google.protobuf.message.Message):
    """TranscribeResponse is the response message containing the transcribed text."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_FIELD_NUMBER: builtins.int
    text: builtins.str
    """The transcribed text."""
    def __init__(
        self,
        *,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["text", b"text"]) -> None: ...

global___TranscribeResponse = TranscribeResponse
